apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-web-deployment
  labels:
    app: ai-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-web
  template:
    metadata:
      labels:
        app: ai-web
    spec:
      containers:
      - name: ai-web
        image: urfucourses/ai_web_demo_app
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ai-web-service
spec:
  type: NodePort
  selector:
    app: ai-web
  ports:
    - protocol: TCP
      port: 8501
      nodePort: 30002
      targetPort: 8501
